export default [
  'SERVICE_METHOD_LOGIN_USER',
  'SERVICE_METHOD_LOGOUT_USER',
  'SERVICE_METHOD_AUTHENTICATE_USER_BY_COOKIE',
  'SERVICE_METHOD_GET_ALL_ADDRESSES',
  'SERVICE_METHOD_GET_ALL_COUNTRIES',
  'SERVICE_METHOD_GET_ALL_CITIES'
];
