version: "3"
services:
  redis:
    container_name: pvocrm_redis
    image: redis
    ports:
      - 6379:6379
  backend:
    container_name: pvocrm_backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile
      args:
        APP_CODE: /usr/src/pvocrm_backend
    depends_on:
      - redis
    environment:
      ENV_BACKEND_APP_PORT: 8080
      ENV_SERVICE_DB_CLIENT: pg
      ENV_SERVICE_DB_USER: postgres
      ENV_SERVICE_DB_HOST: db
      ENV_SERVICE_DB_PASSWORD: docker
      ENV_SERVICE_DB_DATABASE: postgres_pvocrm
      ENV_SERVICE_DB_PORT: 5432
      ENV_SERVICE_REDIS_HOST: redis
      ENV_SERVICE_REDIS_PORT: 6379
      ENV_SERVICE_JWT_SECRET: super_secret
      ENV_SERVICE_JWT_EXPIRY_IN_SECONDS: null
      ENV_SERVICE_CLOUD_S3_ENDPOINT: http://aws_s3:9000
      ENV_SERVICE_CLOUD_S3_ACCESS_KEY_ID: minio_access_key
      ENV_SERVICE_CLOUD_S3_SECRET_ACCESS_KEY: minio_secret_key
  frontend:
    container_name: pvocrm_frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      args:
        APP_CODE: /usr/src/pvocrm_frontend
    depends_on:
      - backend
    environment:
      ENV_FRONTEND_APP_PORT: 3000
  webserver:
    container_name: pvocrm_nginx
    image: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
