version: "3"
services:
  aws_s3:
    container_name: pvocrm_aws_s3
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - ./temp/minio:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data
  db:
    container_name: pvocrm_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres_pvocrm
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/personal/pvocrm
  backend:
    depends_on:
      - aws_s3
      - db
      - redis
    command: npm run dev
    volumes:
      - /usr/src/pvocrm_backend/node_modules
      - ./app/backend:/usr/src/pvocrm_backend
  frontend:
    command: npm run dev
    volumes:
      - /usr/src/pvocrm_frontend/node_modules
      - ./app/frontend:/usr/src/pvocrm_frontend
  webserver:
    volumes:
      - ./app/webserver/nginx.conf:/etc/nginx/nginx.conf
