module.exports = {
  Addresses: require('./Addresses'),
  Cities: require('./Cities'),
  Contracts: require('./Contracts'),
  Contacts: require('./Contacts'),
  ContactNames: require('./ContactNames'),
  Countries: require('./Countries'),
  Documents: require('./Documents'),
  DocumentsCloud: require('./DocumentsCloud'),
  DocumentsTemporary: require('./DocumentsTemporary'),
  Emails: require('./Emails'),
  HistoryManyToManyChanges: require('./HistoryManyToManyChanges'),
  HistoryRecordChanges: require('./HistoryRecordChanges'),
  Invoices: require('./Invoices'),
  LegalEntities: require('./LegalEntities'),
  MailSubjects: require('./MailSubjects'),
  Mails: require('./Mails'),
  MailsAuditTrails: require('./MailsAuditTrails'),
  MailsAuditTrailsDetails: require('./MailsAuditTrailsDetails'),
  MailsPendingActions: require('./MailsPendingActions'),
  NaturalPeople: require('./NaturalPeople'),
  Phones: require('./Phones'),
  Services: require('./Services'),
  Users: require('./Users')
};
