module.exports = {
  Addresses: require('./Addresses'),
  Cities: require('./Cities'),
  Contacts: require('./Contacts'),
  Contracts: require('./Contracts'),
  ContractsServices: require('./ContractsServices'),
  ContractsContacts: require('./ContractsContacts'),
  Countries: require('./Countries'),
  Documents: require('./Documents'),
  Emails: require('./Emails'),
  EntityNames: require('./EntityNames'),
  HistoryManyToManyChanges: require('./HistoryManyToManyChanges'),
  HistoryRecordChanges: require('./HistoryRecordChanges'),
  Invoices: require('./Invoices'),
  LegalEntities: require('./LegalEntities'),
  MailSubjects: require('./MailSubjects'),
  Mails: require('./Mails'),
  MailsAuditTrails: require('./MailsAuditTrails'),
  MailsAuditTrailsDetails: require('./MailsAuditTrailsDetails'),
  MailsPendingActions: require('./MailsPendingActions'),
  NaturalPeople: require('./NaturalPeople'),
  Phones: require('./Phones'),
  Users: require('./Users')
};
