export const RECOMMENDATIONS_CITIES_SET = 'RECOMMENDATIONS_CITIES_SET';
export const RECOMMENDATIONS_CITIES_RESET = 'RECOMMENDATIONS_CITIES_RESET';
export const RECOMMENDATIONS_CITIES_AJAX_START =
  'RECOMMENDATIONS_CITIES_AJAX_START';
export const RECOMMENDATIONS_CITIES_AJAX_FINISH =
  'RECOMMENDATIONS_CITIES_AJAX_FINISH';
