module.exports = ({
  ENV_SERVICE_CLOUD_S3_ACCESS_KEY_ID,
  ENV_SERVICE_CLOUD_S3_SECRET_ACCESS_KEY,
  ENV_SERVICE_CLOUD_S3_ENDPOINT
}) => {
  return {
    s3: {
      accessKeyId: ENV_SERVICE_CLOUD_S3_ACCESS_KEY_ID,
      accessSecretKey: ENV_SERVICE_CLOUD_S3_SECRET_ACCESS_KEY,
      endpoint: ENV_SERVICE_CLOUD_S3_ENDPOINT
    }
  };
};
