module.exports = {
  AUTHENTICATION_ERROR_MESSAGE_FAILED_TO_AUTHENTICATE: 'Failed to authenticate',
  AUTHENTICATION_ERROR_NAME_CONTROLLER: 'AuthenticationInstanceError',
  JWT_ERROR_MESSAGE_TOKEN_EXPIRED: 'JWT token expired',
  JWT_ERROR_NAME_INVALID_TOKEN: 'JsonWebTokenError',
  JWT_ERROR_NAME_TOKEN_EXPIRED: 'TokenExpiredError'
};
