module.exports = [
  'ORCHESTRATOR_METHOD_GET_ALL_ADDRESSES',
  'ORCHESTRATOR_METHOD_LOGIN_USER',
  'ORCHESTRATOR_METHOD_AUTHENTICATE_USER_BY_COOKIE',
  'ORCHESTRATOR_METHOD_GET_ALL_COUNTRIES',
  'ORCHESTRATOR_METHOD_GET_ALL_CITIES',
  'ORCHESTRATOR_METHOD_FILTER_ADDRESSES',
  'ORCHESTRATOR_METHOD_FILTER_COUNTRIES',
  'ORCHESTRATOR_METHOD_FILTER_CITIES',
  'ORCHESTRATOR_METHOD_CREATE_ADDRESS',
  'ORCHESTRATOR_METHOD_FILTER_NATURAL_PEOPLE',
  'ORCHESTRATOR_METHOD_CREATE_NATURAL_PERSON',
  'ORCHESTRATOR_METHOD_FILTER_ENTITY_NAMES',
  'ORCHESTRATOR_METHOD_CREATE_ENTITY_NAME'
];
