module.exports = [
  'REDIS_KEY_ADDRESSES',
  'REDIS_KEY_COUNTRIES',
  'REDIS_KEY_CITIES',
  'REDIS_KEY_NATURAL_PEOPLE_QUICK_LIST',
  'REDIS_KEY_ENTITY_NAMES',
  'REDIS_KEY_USER_EMAIL',
  'REDIS_KEY_ALL_VERSIONS_OF_LEGAL_ENTITIES_QUICK_LIST'
];
