module.exports = [
  'SERVICE_METHOD_LOGIN_USER',
  'SERVICE_METHOD_SIGN_JWT',
  'SERVICE_METHOD_VERIFY_JWT',
  'SERVICE_METHOD_GET_USER_RULES',
  'SERVICE_METHOD_GET_ALL_ADDRESSES',
  'SERVICE_METHOD_GET_ALL_CITIES',
  'SERVICE_METHOD_GET_ALL_COUNTRIES',
  'SERVICE_METHOD_CREATE_ADDRESS',
  'SERVICE_METHOD_GET_ALL_NATURAL_PEOPLE_FOR_QUICK_SEARCH',
  'SERVICE_METHOD_CREATE_NATURAL_PERSON',
  'SERVICE_METHOD_SET_REDIS_VALUE',
  'SERVICE_METHOD_GET_REDIS_VALUE',
  'SERVICE_METHOD_GET_ALL_ENTITY_NAMES'
];
