module.exports = [
  'SERVICE_METHOD_LOGIN_USER',
  'SERVICE_METHOD_SIGN_JWT',
  'SERVICE_METHOD_VERIFY_JWT',
  'SERVICE_METHOD_GET_USER_RULES',
  'SERVICE_METHOD_GET_ALL_ADDRESSES',
  'SERVICE_METHOD_GET_ALL_CITIES',
  'SERVICE_METHOD_GET_ALL_COUNTRIES'
];
